spring.application.name=javaProjectTu
spring.datasource.url=jdbc:postgresql://localhost:5432/javacourse_db
spring.datasource.username=javaclass_user
spring.datasource.password=StrongPass123
spring.jpa.hibernate.ddl-auto=create
spring.profiles.active=dev